### ISSUE TITLE
`rtx config-file generate`?

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#1116]
I had an idea for a command that would scaffold out an `.rtx.toml` with some common examples. Thoughts?

In the past I thought it not necessary since you can just use `rtx use` but I think it could display some more advanced config like virtualenv's for python and `[env]` sections

Other name ideas:
* `rtx config-generate`
* `rtx config --generate`
* `rtx toml`
* `rtx config.toml`? don't know if clap allows this though

**Comment by Aeron** [comment]
If it’s an example of all possible options and formatting, the second option suits better, in my opinion. Or even `rtx config --example` to clarify it’s not necessarily the configuration a user wants in a particular case.

The only problem is that there is no config command, so it’s (kind of) irresponsible to use the `config` namespace for the only option/flag available. The same goes for the `config-file generate` variant. If there are plans to utilize it more, then it’s ok.

Otherwise, maybe `rtx use --example` will suit better since it’s somewhat directly relevant.

**Comment by jdx** [comment]
went ahead and added it as `rtx config generate`. There is also a `rtx config` that lists all the config files.
