### ISSUE TITLE
make `config` optional in commands

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#412]
Right now every command has a `Config` object on it. This is relatively expensive to create since it involves resolving all of the config files. It might be possible to refactor the code such that each command could declare whether or not it needs the config object.

One area this is a problem is that if the config parsing causes a panic it prevents the command from running so you can't do `rtx plugins update` or `rtx self-update` to update the code if it's currently causing a panic.

**Comment by jdxcode** [comment]
a naive solution might be to make plugin scripts all warn instead of error out. I've changed my mind about this a couple of times now. Originally it errored, then I made it warn, and now it's kind of a mix. Certain things will error and certain things will warn.

I'm not sure what the right behavior is here. If a single plugin or config file is causing a failure, should that block everything or not?
