### ISSUE TITLE
RTX_EXPERIMENTAL=0

### ISSUE THREAD

**Issue by jdx** [jdx/rtx#533]
this should disable experimental mode even if it is enabled in the global config:

```
$ rtx settings set experimental true
$ RTX_EXPERIMENTAL=0 rtx settings get experimental
false
```

**Comment by jdxcode** [comment]
this is unfortunately going to be a pain to fix. And I very much want to refactor the settings generally since that is probably now the oldest and worst part of the codebase with a ton of yak shaving involved in adding new settings.

**Comment by 0kate** [comment]
Hello! I'm checking codes about this Issue.

I think the orders of configuration values should be changed.
Currently, the first values are loaded from env var (fallbacked by default values) and that will be overlayed by values in the configuration file.
However, I think env vars should be loaded lastly and overlay values from other sources. (means putting env vars before others)

(Env || Default) --(overlay)--> values in configuration
↓
Default --(overlay)--> values in configuration --(overlay)--> env vars

**Comment by 0kate** [comment]
@jdxcode 
Hello! I'm checking codes about this Issue.

I think the orders of configuration values should be changed.
Currently, the first values are loaded from env var (fallbacked by default values) and that will be overlayed by values in the configuration file.
However, I think env vars should be loaded lastly and overlay values from other sources. (means putting env vars before others)

(Env || Default) --(overlay)--> values in configuration
↓
Default --(overlay)--> values in configuration --(overlay)--> env vars

If that way is not bad, Could I pick this up?

**Comment by jdxcode** [comment]
yep, agreed, that sounds like the right approach. I will warn you though this may be a tricky issue since that code is truly awful.

**Comment by jdxcode** [comment]
I think it's split across rtx_toml.rs, env.rs, and settings.rs

**Comment by 0kate** [comment]
Thank you for the confirmation! I will join the rtx discord channel and chat you when I'm confusing.
When I finish changing codes, I inform you to request review 🙏

**Comment by jdxcode** [comment]
one thing I was having a chat with @ilovesegfault about was that it would be nice to link at least some of the arguments (not this one) to the CLI flags. For example `rtx --log-level=info`. That feels like a hard problem though. It's related to this though because if we're refactoring the (currently horrific) settings logic it would be good to have CLI flags in the back of our mind at least.

**Comment by jdxcode** [comment]
one thing I was having a chat with @lovesegfault about was that it would be nice to link at least some of the arguments (not this one) to the CLI flags. For example `rtx --log-level=info`. That feels like a hard problem though. It's related to this though because if we're refactoring the (currently horrific) settings logic it would be good to have CLI flags in the back of our mind at least.

**Comment by jdxcode** [comment]
I used [figment](https://docs.rs/figment/latest/figment/index.html) on another project which works pretty well at solving this problem of hooking up config files, env vars, and CLI flags.

I don't want to bring on a dependency for rtx for this particular problem, but I think figment has some patterns that might be useful to think about here.
