### ISSUE TITLE
RTX_*  from ~/.config/rtx/config.toml not taking effect for rtx itself

### ISSUE THREAD

**Issue by scop** [jdx/rtx#768]
**Describe the bug**

RTX_GO_SET_GOROOT and RTX_GO_SET_GOPATH do not seem to take effect for rtx itself when set in ~/.config/rtx/config,toml. They do get set, but so do GOROOT and GOPATH.

If set in a shell startup file, they do work as expected and prevent GOROOT and GOPATH from being set.

Perhaps the env settings from rtx config.toml take effect too late?

**To Reproduce**

```shellsession
$ cat .config/rtx/config.toml
[env]
RTX_GO_SET_GOROOT = "0"
RTX_GO_SET_GOPATH = "0"

[tools]
go = "1.20.7"
$ ssh localhost
$ env | grep GO
GOROOT=/home/scop/.local/share/rtx/installs/go/1.20.7/go
RTX_GO_SET_GOPATH=0
RTX_GO_SET_GOROOT=0
GOPATH=/home/scop/.local/share/rtx/installs/go/1.20.7/packages
```

**Expected behavior**

GOROOT and GOPATH should not have been set.

**`rtx doctor` output**

```
rtx version:
  1.35.8 linux-x64 (2589c72 2023-08-02)

build:
  Target: x86_64-unknown-linux-gnu
  Features: DEFAULT, NATIVE_TLS
  Built: Wed, 02 Aug 2023 20:25:37 +0000
  Rust Version: rustc 1.71.0 (8ede3aae2 2023-07-12)
  Profile: release

shell:
  /bin/bash
  GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
  Copyright (C) 2019 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

  This is free software; you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.

rtx data directory:
  /home/scop/.local/share/rtx

rtx environment variables:
  RTX_GO_SET_GOPATH=0
  RTX_GO_SET_GOROOT=0
  RTX_SHELL=bash

settings:
  {"always_keep_download": "false", "always_keep_install": "false", "asdf_compat": "false", "disable_default_shorthands": "false", "disable_tools": "[]", "experimental": "false", "jobs": "4", "legacy_version_file": "true", "legacy_version_file_disable_tools": "[]", "log_level": "INFO", "missing_runtime_behavior": "warn", "plugin_autoupdate_last_check_duration": "10080", "raw": "false", "trusted_config_paths": "[]", "verbose": "false"}

config files:
  /home/scop/.config/rtx/config.toml

plugins:
  go       (core)
  java     (core)
  node     (core)
  python   (core)
  ruby     (core)

toolset:
  go@1.20.7

No problems found
```

**Additional context**

**Comment by jdxcode** [comment]
this is the same root cause as https://github.com/jdxcode/rtx/issues/702

unfortunately it isn't an easy fix. The entire env var code needs to not be globally memoized like it is now which won't be a simple fix.

**Comment by jdxcode** [comment]
sort of related to #533 too. I think I want to completely refactor config/settings/env alongside config files and CLI flags. I think all of these should be able to output a map of configuration, something like:

```
{
  "gopath": "...",
  "verbose": 1
}
```

for all config settings regardless of where they come from. Then as the CLI is initialized it can layer on each type. This way what we can do with env vars is load the initial env vars we need, then once we parse a config file we can reset that env var config and replace it with new env vars from a config file.

Not sure if that makes sense, it's more notes for myself than it is for you since I'll probably need to make this change. It's significant.

The nice thing is it will clean up the settings code which is probably the worst part of the codebase right now.

**Comment by scop** [comment]
Thanks for consideration. I saw #702 and thought it's related, but I'm too new to rtx's workings that I'd be able to tell if it was the same thing. Feel free to close this if you think it's more noise than useful to have around.
